# this is a Dockerile for notesapp-server
FROM node:20.11.0

WORKDIR /app

COPY ./package*.json ./

RUN npm i

COPY . .

RUN npx prisma generate
RUN npx prisma db push
EXPOSE 5000

CMD ["npm", "run",  "dev"]
