FROM node:22.22.2-alpine

WORKDIR /app
COPY ./package*.json ./
RUN npm i

COPY . .
COPY .env ./

RUN npx prisma migrate dev
RUN npx prisma generate
RUN npx prisma migrate status

CMD ["sh", "-c", "npx tsc && npm run dev"]
